default_platform(:android)

AAB = File.expand_path("../../../app/build/outputs/bundle/release/app-release.aab", __dir__)

platform :android do
  desc "Upload the release AAB to the internal track"
  lane :internal do
    upload_to_play_store(
      track: "internal",
      aab: AAB,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "completed"
    )
  end

  desc "Promote / upload the release AAB to production"
  lane :release do
    upload_to_play_store(
      track: "production",
      aab: AAB,
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "completed"
    )
  end
end
